networks:
    laravel:
        driver: bridge

services:
    app:
         build:
             context: .
             dockerfile: Dockerfile
             target: app
         container_name: app
         restart: unless-stopped
         ports:
             - 9000:9000
         depends_on:
             - nginx
             - db
         volumes:
             - .:/var/www:delegated
         networks:
             - laravel
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/conf.d/vhost.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www:delegated
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        networks:
            - laravel
